name: Cypress Tests
on: [push]
jobs:
 chrome:
   runs-on: ubuntu-latest
   name: E2E Tests on Chrome
   steps:
     - uses: actions/checkout@v3
     - uses: cypress-io/github-action@v5
       with:
         command: npx cypress run
         browser: chrome
